mutation createBankAccount($input: createBankAccountInput!) {
  createBankAccount(input: $input) {
    id
    name
    number
    isVerified
    isActive
    currency
    createdAt
    updatedAt
  }
}
