fragment financial on Financial {
  id
  annualIncomeBracket
  expectedTradingVolume
  investmentExperience
  investmentObjective
  liquidAssets
  netWorthBracket
  primaryIncomeSource
  riskTolerance
  year
  updatedAt
}
