mutation resetPassword($confirmationId: ID!, $password: String!, $passwordConfirmation: String!) {
  resetPassword(input: { confirmationId: $confirmationId, password: $password, passwordConfirmation: $passwordConfirmation })
}
