query states($first: Int, $after: String, $filter: StateFilter, $sort: SortFilter) {
  states(first: $first, after: $after, filter: $filter, sort: $sort) {
    nodes {
      id
      name
      code
    }
  }
}
